server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/postgres}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: "db.changelog/db.changelog.yml"

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher